services:
  postgres:
    image: postgres:16-alpine
    container_name: detection-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: detection_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
